# Generated by Django 2.1.5 on 2020-06-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200612_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in U$S', max_digits=4),
        ),
    ]
