# Generated by Django 2.1.5 on 2020-06-24 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_auto_20200623_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='dinnerplatter',
            field=models.ManyToManyField(blank=True, to='orders.DinnerPlatter'),
        ),
        migrations.AddField(
            model_name='order',
            name='pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='order',
            name='salad',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.AddField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
    ]
