# Generated by Django 2.1.5 on 2020-06-30 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200630_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinnerplatter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.DinnerPlatter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='salad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Sub'),
        ),
    ]
