# Generated by Django 2.1.5 on 2020-07-01 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200701_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ManyToManyField(related_name='orders', to='orders.Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
    ]
