# Generated by Django 2.1.5 on 2020-07-02 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200702_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_pizza',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='special_pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='order',
            name='special',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Pizza'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Topping'),
        ),
        migrations.DeleteModel(
            name='Special_Pizza',
        ),
    ]
